### ISSUE TITLE
Fix crush in jungle lvl

### ISSUE THREAD

**Issue by Oleg-designer** [QuasarApp/Crawl#103]
When level start the game was crush with this text in console: 

QQmlEngine::setContextForObject(): Object already has a QQmlContext
qml: wrong viewTemplate in model qrc:/qml/Models/Ground.qml:9 "GraphicItem" version 1.0 is defined more than once in module "CrawlModule"

qml: wrong viewTemplate in model qrc:/qml/Models/Ground.qml:9 "GraphicItem" version 1.0 is defined more than once in module "CrawlModule"

qml: wrong viewTemplate in model qrc:/qml/Models/Ground.qml:9 "GraphicItem" version 1.0 is defined more than once in module "CrawlModule"

Segmentation fault (core dumped)

**Comment by EndrII** [comment]
see 39185ca17f8271e5738d0a59caf38475c802d7f4
